### ISSUE TITLE
Why not show the complaints on a map?

### ISSUE THREAD

**Issue by fedex1** [NewYorkCityCouncil/fullstack-coding-challenge#3]
Mapbox does that very well

See [map link](https://api.mapbox.com/styles/v1/cityregister/cinyzwrq10003a4npcz3lb1t3.html?fresh=true&title=true&access_token=pk.eyJ1IjoiY2l0eXJlZ2lzdGVyIiwiYSI6ImNpbnhrMHJhcjE3OHh1Mm0zbnJ6YXZseWcifQ.1TP2MzhnoJCdzX_qYns1BA#16.07/40.69006/-73.943239)

![Screenshot from 2019-12-15 21-21-24](https://user-images.githubusercontent.com/167614/70874605-e1a23380-1f80-11ea-8465-35afb609483d.png)

This already works and is updated in real time.

**Comment by JC-NYCC-1227** [comment]
Thanks for your comment and we appreciate the helpful suggestion!

The repo is actually just meant to contain "starter code" for a coding challenge and not actually address council member requests. We actually already have a private application that uses the same data and, as you suggested, displays the metrics in charts and maps in realtime!

**Comment by fedex1** [comment]
Thanks for feedback.  And is there any reason that private application is not available to the public?

**Comment by JC-NYCC-1227** [comment]
At this time the application is still under heavy development and requires further testing as well as user feedback.
